# Jenkins Cloud Formation To Do
# x 1. Create tags
# 2. Create name with GUID or portion of instance id
# x 3. Termination Protection

AWSTemplateFormatVersion: 2010-09-09
Metadata:
  'AWS::CloudFormation::Designer':
    bc1b7f29-9c3b-4ee9-9bc0-f69df7341413:
      size:
        width: 60
        height: 60
      position:
        x: 30
        'y': 60
      z: 0
      embeds: []
Resources:
  JenkinsServer:
    Type: 'AWS::EC2::Instance'
    Properties:
      Tags:
        - Key: DIME
          Value: '22476'
        - Key: DIME Link
          Value: 'https://equityresidential.quickbase.com/db/bb4qdnypp?a=dr&r=x8n&rl=st'
        - Key: Project
          Value: 'Jenkins POC'
      ImageId: ami-0f7919c33c90f5b58
      InstanceType: t2.micro
      KeyName: eqr-ohio
      DisableApiTermination: 'true'
      NetworkInterfaces:
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: subnet-b7a23afb
          GroupSet:
            - sg-0a391ec88b5acd095
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              sudo mkdir /var/lib/jenkins
            - |
              sudo useradd -d /var/lib/jenkins jenkins
            - |
              sudo chown jenkins:jenkins /var/lib/jenkins
            - |
              sudo mkdir /var/lib/jenkins/.ssh
            - |
              ssh-keygen -b 2048 -t rsa -f /tmp/id_rsa -q -N ""
            - |
              sudo cp /tmp/id_rsa /var/lib/jenkins/.ssh/authorized_keys
            - |
              sudo cp /tmp/id_rsa.pub /var/lib/jenkins/.ssh/
            - |
              sudo yum install java-1.8.0-openjdk-devel -y
            - |
              sudo yum install git -y
            - |
              sudo yum install maven -y
            - >
              sudo wget -O /etc/yum.repos.d/jenkins.repo
              http://pkg.jenkins.io/redhat-stable/jenkins.repo
            - >
              sudo rpm --import
              http://pkg.jenkins.io/redhat-stable/jenkins.io.key
            - |
              sudo yum install jenkins -y
            - |
              sudo yum upgrade -y
            - |
              sudo service jenkins start
    Metadata:
      'AWS::CloudFormation::Designer':
        id: bc1b7f29-9c3b-4ee9-9bc0-f69df7341413
